Repository euphony-io/euphony, pull requests merged in 2022-08, with the labels that each got.

#183 Release: v0.8.0.1
  .github/workflows/android.yml
  .github/workflows/publish.yml
  README.md
  build.gradle
  euphony/build.gradle
  euphony/publish.gradle
  euphony/src/androidTest/java/co/euphony/tx/EuTxManagerTest.java
  euphony/src/main/cpp/CMakeLists.txt
  euphony/src/main/cpp/arms/kiss_fft.h
  euphony/src/main/cpp/core/BlueFFT.h
  euphony/src/main/cpp/core/FFTModel.h
  euphony/src/main/cpp/core/FFTProcessor.h
  euphony/src/main/cpp/core/FSK.h
  euphony/src/main/cpp/core/RxEngine.h
  euphony/src/main/cpp/core/TxEngine.h
  euphony/src/main/cpp/core/WakeUpFFTSensor.h
  euphony/src/main/cpp/core/WakeUpSensor.h
  euphony/src/main/cpp/core/source/BlueFFT.cpp
  euphony/src/main/cpp/core/source/FFTModel.cpp
  euphony/src/main/cpp/core/source/FFTProcessor.cpp
  euphony/src/main/cpp/core/source/FSK.cpp
  euphony/src/main/cpp/core/source/RxEngine.cpp
  euphony/src/main/cpp/core/source/TxEngine.cpp
  euphony/src/main/cpp/core/source/WakeUpFFTSensor.cpp
  euphony/src/main/cpp/native-connector.cpp
  euphony/src/main/cpp/tests/BlueFFTTest.cpp
  euphony/src/main/cpp/tests/CMakeLists.txt
  euphony/src/main/cpp/tests/FFTProcessorTest.cpp
  euphony/src/main/cpp/tests/FFTTest.cpp
  euphony/src/main/cpp/tests/wakeUpFFTSensorTest.cpp
  euphony/src/main/java/co/euphony/common/EuNativeConnector.java
  euphony/src/main/java/co/euphony/rx/EuRxManager.java
  euphony/src/main/java/co/euphony/tx/EuTxManager.java
  euphony/src/main/java/co/euphony/tx/EuTxNativeConnector.java
  publish-root.gradle
Labels: enhancement

#188 Made FFTHelper class to prevent violation of SRP of FSK class
  euphony/src/main/cpp/CMakeLists.txt
  euphony/src/main/cpp/core/FFTHelper.h
  euphony/src/main/cpp/core/FSK.h
  euphony/src/main/cpp/core/Wave.h
  euphony/src/main/cpp/core/WaveBuilder.h
  euphony/src/main/cpp/core/source/FFTHelper.cpp
  euphony/src/main/cpp/core/source/FSK.cpp
  euphony/src/main/cpp/core/source/WakeUpFFTSensor.cpp
  euphony/src/main/cpp/core/source/Wave.cpp
  euphony/src/main/cpp/core/source/WaveBuilder.cpp
  euphony/src/main/cpp/tests/BlueFFTTest.cpp
  euphony/src/main/cpp/tests/CMakeLists.txt
  euphony/src/main/cpp/tests/FFTHelperTest.cpp
  euphony/src/main/cpp/tests/FFTProcessorTest.cpp
  euphony/src/main/cpp/tests/wakeUpFFTSensorTest.cpp
  euphony/src/main/cpp/tests/waveBuilderTest.cpp
Labels: enhancement

#185 Update PREREQUISITE.md
  PREREQUISITE.md
Labels: documentation

#194 Optimize Github Action to ignore markdown files (#193)
  .github/workflows/android.yml
Labels: Clean Code

#123 Add ASK class
  euphony/src/main/cpp/CMakeLists.txt
  euphony/src/main/cpp/core/ASK.h
  euphony/src/main/cpp/core/Definitions.h
  euphony/src/main/cpp/core/ModemFactory.h
  euphony/src/main/cpp/core/Wave.h
  euphony/src/main/cpp/core/WaveBuilder.h
  euphony/src/main/cpp/core/source/ASK.cpp
  euphony/src/main/cpp/core/source/Wave.cpp
  euphony/src/main/cpp/core/source/WaveBuilder.cpp
  euphony/src/main/cpp/tests/ASKTest.cpp
  euphony/src/main/cpp/tests/CMakeLists.txt
Labels: enhancement, feature

#206 Resolved fail case of unit-test for ASK
  euphony/src/main/cpp/core/Wave.h
  euphony/src/main/cpp/core/WaveBuilder.h
  euphony/src/main/cpp/core/source/ASK.cpp
  euphony/src/main/cpp/core/source/Wave.cpp
  euphony/src/main/cpp/core/source/WaveBuilder.cpp
  euphony/src/main/cpp/tests/ASKTest.cpp
Labels: bug

#189 feat: support kotlin, jetpack compose, TxRxChecker
  .github/workflows/android.yml
  build.gradle
  euphony/build.gradle
  euphony/src/androidTest/java/co/euphony/ui/TxRxCheckerImplTest.kt
  euphony/src/main/java/co/euphony/common/Constants.java
  euphony/src/main/java/co/euphony/ui/TxRxChecker.kt
  euphony/src/main/java/co/euphony/ui/theme/Color.kt
  euphony/src/main/java/co/euphony/ui/theme/Type.kt
  euphony/src/main/java/co/euphony/ui/viewmodel/TxRxCheckerViewModel.kt
  euphony/src/main/java/co/euphony/util/EuCodec.java
  euphony/src/main/java/co/euphony/util/EuCodec.kt
  euphony/src/test/java/euphony/lib/ui/viewmodel/TxRxCheckerViewModelTest.kt
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: feature

#208 Update documentation for v0.8.1
  PREREQUISITE.md
  README.md
  euphony/publish.gradle
Labels: documentation

#211 Made java-sample module for euphony library
  java-sample/.gitignore
  java-sample/build.gradle
  java-sample/proguard-rules.pro
  java-sample/src/androidTest/java/co/euphony/sample/ExampleInstrumentedTest.java
  java-sample/src/main/AndroidManifest.xml
  java-sample/src/main/java/co/euphony/sample/MainActivity.java
  java-sample/src/main/java/co/euphony/sample/fragments/MainFragment.java
  java-sample/src/main/java/co/euphony/sample/fragments/rx/EuPIRxViewMaker.java
  java-sample/src/main/java/co/euphony/sample/fragments/rx/RxCommunicationFragment.java
  java-sample/src/main/java/co/euphony/sample/fragments/rx/RxEuPIFragment.java
  java-sample/src/main/java/co/euphony/sample/fragments/tx/TxCommunicationFragment.java
  java-sample/src/main/java/co/euphony/sample/fragments/tx/TxEuPIFragment.java
  java-sample/src/main/res/drawable-v24/ic_launcher_foreground.xml
  java-sample/src/main/res/drawable/ic_launcher_background.xml
  java-sample/src/main/res/layout/activity_main.xml
  java-sample/src/main/res/layout/fragment_main.xml
  java-sample/src/main/res/layout/fragment_rx_communication.xml
  java-sample/src/main/res/layout/fragment_rx_eupi.xml
  java-sample/src/main/res/layout/fragment_tx_communication.xml
  java-sample/src/main/res/layout/fragment_tx_eupi.xml
  java-sample/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  java-sample/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  java-sample/src/main/res/mipmap-hdpi/ic_launcher.webp
  java-sample/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  java-sample/src/main/res/mipmap-mdpi/ic_launcher.webp
  java-sample/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  java-sample/src/main/res/mipmap-xhdpi/ic_launcher.webp
  java-sample/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  java-sample/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  java-sample/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  java-sample/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  java-sample/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  java-sample/src/main/res/navigation/nav_graph.xml
  java-sample/src/main/res/values-night/themes.xml
  java-sample/src/main/res/values/colors.xml
  java-sample/src/main/res/values/strings.xml
  java-sample/src/main/res/values/themes.xml
  java-sample/src/test/java/co/euphony/sample/ExampleUnitTest.java
  settings.gradle
Labels: enhancement, Clean Code
