Repository euphony-io/euphony, pull requests merged in 2022-09, with the labels that each got.

#180 Update README, add Euterpe sample project (#178)
  README.md
Labels: Sample Proposal

#181 update README, add Account Touch Project (#177)
  README.md
Labels: Sample Proposal

#216 Update documentation for v0.8.1.1
  PREREQUISITE.md
  README.md
  euphony/publish.gradle
Labels: documentation

#217 Add an advanced log for calling listen() without permission #205
  euphony/src/androidTest/java/co/euphony/rx/EuRxManagerTest.kt
  euphony/src/main/java/co/euphony/rx/AudioRecorder.java
  euphony/src/main/java/co/euphony/rx/EuRxManager.java
Labels: enhancement

#228 Optimize Github Action for Compose tests
  .github/workflows/android.yml
Labels: enhancement

#238 Update documentation for v0.8.1.2
  PREREQUISITE.md
  README.md
  euphony/publish.gradle
Labels: documentation

#251 Delete Travis CI (#248)
  .travis.yml
Labels: Clean Code

#253 Update README.md, add sample project: order-with (#179)
  README.md
Labels: Sample Proposal

#252 Refactor package name of unit test
  euphony/src/test/java/co/euphony/receiver/ReceiverUnitTest.java
  euphony/src/test/java/co/euphony/transmitter/TransmitterUnitTest.java
  euphony/src/test/java/co/euphony/ui/viewmodel/TxRxCheckerViewModelTest.kt
  euphony/src/test/java/co/euphony/util/EuTimerTest.kt
  euphony/src/test/java/co/euphony/util/UtilUnitTest.java
Labels: Clean Code

#257 fix: package name
  euphony/src/test/java/co/euphony/receiver/ReceiverUnitTest.java
  euphony/src/test/java/co/euphony/transmitter/TransmitterUnitTest.java
  euphony/src/test/java/co/euphony/ui/viewmodel/TxRxCheckerViewModelTest.kt
  euphony/src/test/java/co/euphony/util/EuTimerTest.kt
  euphony/src/test/java/co/euphony/util/UtilUnitTest.java
Labels: bug

#244 Refactor EuTxManager Java to Kotlin
  euphony/src/androidTest/java/co/euphony/tx/EuTxManagerTest.java
  euphony/src/main/java/co/euphony/tx/EuTxManager.java
  euphony/src/main/java/co/euphony/tx/EuTxManager.kt
Labels: enhancement, osca-22

#268 Apply noise filter on eupi
  euphony/src/main/java/co/euphony/rx/EuPI.java
Labels: enhancement

#267 [FEATURE] Apply Singleton pattern to EuTxManager
  GETTING_STARTED.md
  GETTING_STARTED_KR.md
  README.md
  euphony/src/androidTest/java/co/euphony/tx/EuTxManagerTest.java
  euphony/src/main/java/co/euphony/tx/EuTxManager.kt
  euphony/src/main/java/co/euphony/ui/TxRxChecker.kt
  java-sample/src/main/java/co/euphony/sample/fragments/tx/TxCommunicationFragment.java
  java-sample/src/main/java/co/euphony/sample/fragments/tx/TxEuPIFragment.java
Labels: enhancement, documentation, osca-22

#261 feat: support EuphonyRxPanel component (#237)
  euphony/src/androidTest/java/co/euphony/ui/EuphonyRxPanelTest.kt
  euphony/src/main/java/co/euphony/common/Constants.java
  euphony/src/main/java/co/euphony/ui/EuphonyRxPanel.kt
  euphony/src/main/java/co/euphony/ui/viewmodel/EuphonyRxPanelViewModel.kt
Labels: feature, osca-22
